[package]
name = "RUST"
version = "0.1.0"
edition = "2024"

[dependencies]
solana-client = "3.0.10"
solana-commitment-config = "3.0.0"
solana-sdk = "3.0.0"
tokio = { version = "1", features = ["full"] }
